* The Great Ideas of Philosophy, 2nd Edition
** Lecture 1 - From the Upanishads to Homer
*** The Problem of Knowledge
    How do we know anything and on what basis do we seek answers?
*** The Problem of Conduct
    How one's life should be lived? What do we want to maximize and how should we do it?
*** The Problem of Governance
    On what basis does society emerge? What is the basis for social action?
*** The Hindu Upanishads written around ___ provide mythic answers to philosoophical questions
    800 BC
    They are The Vedas for popular consumption.
*** Atman
    The cosmic soul which generates reality through its presence. Individuals are one with the Atman in that they are a microcosmic expression of the macrocosm.
*** Brahma
    The knowledge and search for knowledge that renders life meaningful.
*** Homer is an ancient Greek (possibly several Greeks) from around ___ who wrote ___?  
    750 BC
    Epic poems such as the Iliad and Odyssey
*** According to Homer, who is the person in the worst imaginable situation? 
    "the heartless, lawless, stateless man"
*** Ludwig Wittgenstein (1880s-1950s) on what the mission of a philsopher is
    "to show the fly the way out of the bottle"
** Lecture 2 - Philosophy - Did the Greeks Invent It?
*** What is the etymology of the word /Philosophy/
    Love of wisdom
** Lecture 3 - Pythagoras and the Divinity of Number
*** Pythagoras lived in the _____ century  
    6th BC - 570-495 BC
*** Pythagoras thought "the body is the material manifestation of something that _____
    ...is, fundamentally, not material but relational."
*** Pythagorean Theorem is that
    \begin{equation}
    a^2+b^2=c^2
    \end{equation}
** Lecture 4 - What is There?
***  
  
