* The Great Ideas of Philosophy, 2nd Edition
** Lecture 1 - From the Upanishads to Homer
*** The Problem of Knowledge
    How do we know anything and on what basis do we seek answers?
*** The Problem of Conduct
    How one's life should be lived? What do we want to maximize and how should we do it?
*** The Problem of Governance
    On what basis does society emerge? What is the basis for social action?
*** The Hindu Upanishads written around ___ provide mythic answers to philosoophical questions
    800 BC
    They are The Vedas for popular consumption.
*** Atman
    The cosmic soul which generates reality through its presence. Individuals are one with the Atman in that they are a microcosmic expression of the macrocosm.
*** Brahma
    The knowledge and search for knowledge that renders life meaningful.
*** Homer is an ancient Greek (possibly several Greeks) from around ___ who wrote ___?  
    750 BC
    Epic poems such as the Iliad and Odyssey
*** According to Homer, who is the person in the worst imaginable situation? 
    "the heartless, lawless, stateless man"
*** Ludwig Wittgenstein (1880s-1950s) on what the mission of a philsopher is
    "to show the fly the way out of the bottle"
** Lecture 2 - Philosophy - Did the Greeks Invent It?
*** What is the etymology of the word /Philosophy/
    Love of wisdom
** Lecture 3 - Pythagoras and the Divinity of Number
*** Pythagoras lived in the _____ century  
    6th BC - 570-495 BC
*** Pythagoras thought "the body is the material manifestation of something that _____
    ...is, fundamentally, not material but relational."
*** Pythagorean Theorem is that
    \begin{equation}
    a^2+b^2=c^2
    \end{equation}
** Lecture 4 - What is There?
*** The word metaphysics derives from the writings of _____ and means _____
    Aristotle, “after the physics,”
*** What questions does metaphysics ask?
    "What is there?" and "How do I know?"
*** What are the two branches of metaphysics?
    Epistemology and Ontology
*** What are the two methods of exploring "What is there?"
    Rationalistic and perception
*** What is epistemology?
    Exploration of "How do I know?". The study of criticism, and refinement of our modes of knowing. What is our method of discover for discoering the truth about the world?
*** What is epistemic justification? 
    How do we justify our beliefs? Eg. that the rules of math and physics would be the same tomorrow as today
*** What is the materialist answer Democritus of Abdera gives to what it means for something to exist?
    That everything that exists is made of indivisible atoms, including thoughts and dreams.
*** In the Dialogs of Plato, Protagoras says "Man is the measure of all things". What does this mean?
    Perception determines the reality of each person. One person's reality can claim as much ontological validity as any other. The only grounding is the experiences of one's lifetime.
** Lecture 5 - The Greek Tragedians on Man's Fate
***   
  
